# Generated by Django 3.2.8 on 2021-11-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Budget ID')),
                ('owner_phone', models.CharField(max_length=50, verbose_name='Owner phone')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('codename', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Codename')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expenses', 'Expenses')], max_length=255, verbose_name='Category type')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Record ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.budget')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.category')),
            ],
        ),
    ]
